package com.example.compose
import android.app.Activity
import android.os.Build
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.material3.Typography
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.platform.LocalContext

private val lightScheme = lightColorScheme(
    primary = primaryLight,
    surface-tint = surface-tintLight,
    on-primary = on-primaryLight,
    primary-container = primary-containerLight,
    on-primary-container = on-primary-containerLight,
    secondary = secondaryLight,
    on-secondary = on-secondaryLight,
    secondary-container = secondary-containerLight,
    on-secondary-container = on-secondary-containerLight,
    tertiary = tertiaryLight,
    on-tertiary = on-tertiaryLight,
    tertiary-container = tertiary-containerLight,
    on-tertiary-container = on-tertiary-containerLight,
    error = errorLight,
    on-error = on-errorLight,
    error-container = error-containerLight,
    on-error-container = on-error-containerLight,
    background = backgroundLight,
    on-background = on-backgroundLight,
    surface = surfaceLight,
    on-surface = on-surfaceLight,
    surface-variant = surface-variantLight,
    on-surface-variant = on-surface-variantLight,
    outline = outlineLight,
    outline-variant = outline-variantLight,
    shadow = shadowLight,
    scrim = scrimLight,
    inverse-surface = inverse-surfaceLight,
    inverse-on-surface = inverse-on-surfaceLight,
    inverse-primary = inverse-primaryLight,
    primary-fixed = primary-fixedLight,
    on-primary-fixed = on-primary-fixedLight,
    primary-fixed-dim = primary-fixed-dimLight,
    on-primary-fixed-variant = on-primary-fixed-variantLight,
    secondary-fixed = secondary-fixedLight,
    on-secondary-fixed = on-secondary-fixedLight,
    secondary-fixed-dim = secondary-fixed-dimLight,
    on-secondary-fixed-variant = on-secondary-fixed-variantLight,
    tertiary-fixed = tertiary-fixedLight,
    on-tertiary-fixed = on-tertiary-fixedLight,
    tertiary-fixed-dim = tertiary-fixed-dimLight,
    on-tertiary-fixed-variant = on-tertiary-fixed-variantLight,
    surface-dim = surface-dimLight,
    surface-bright = surface-brightLight,
    surface-container-lowest = surface-container-lowestLight,
    surface-container-low = surface-container-lowLight,
    surface-container = surface-containerLight,
    surface-container-high = surface-container-highLight,
    surface-container-highest = surface-container-highestLight,
)

private val lightHighContrastScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    surface-tint = surface-tintLightHighContrast,
    on-primary = on-primaryLightHighContrast,
    primary-container = primary-containerLightHighContrast,
    on-primary-container = on-primary-containerLightHighContrast,
    secondary = secondaryLightHighContrast,
    on-secondary = on-secondaryLightHighContrast,
    secondary-container = secondary-containerLightHighContrast,
    on-secondary-container = on-secondary-containerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    on-tertiary = on-tertiaryLightHighContrast,
    tertiary-container = tertiary-containerLightHighContrast,
    on-tertiary-container = on-tertiary-containerLightHighContrast,
    error = errorLightHighContrast,
    on-error = on-errorLightHighContrast,
    error-container = error-containerLightHighContrast,
    on-error-container = on-error-containerLightHighContrast,
    background = backgroundLightHighContrast,
    on-background = on-backgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    on-surface = on-surfaceLightHighContrast,
    surface-variant = surface-variantLightHighContrast,
    on-surface-variant = on-surface-variantLightHighContrast,
    outline = outlineLightHighContrast,
    outline-variant = outline-variantLightHighContrast,
    shadow = shadowLightHighContrast,
    scrim = scrimLightHighContrast,
    inverse-surface = inverse-surfaceLightHighContrast,
    inverse-on-surface = inverse-on-surfaceLightHighContrast,
    inverse-primary = inverse-primaryLightHighContrast,
    primary-fixed = primary-fixedLightHighContrast,
    on-primary-fixed = on-primary-fixedLightHighContrast,
    primary-fixed-dim = primary-fixed-dimLightHighContrast,
    on-primary-fixed-variant = on-primary-fixed-variantLightHighContrast,
    secondary-fixed = secondary-fixedLightHighContrast,
    on-secondary-fixed = on-secondary-fixedLightHighContrast,
    secondary-fixed-dim = secondary-fixed-dimLightHighContrast,
    on-secondary-fixed-variant = on-secondary-fixed-variantLightHighContrast,
    tertiary-fixed = tertiary-fixedLightHighContrast,
    on-tertiary-fixed = on-tertiary-fixedLightHighContrast,
    tertiary-fixed-dim = tertiary-fixed-dimLightHighContrast,
    on-tertiary-fixed-variant = on-tertiary-fixed-variantLightHighContrast,
    surface-dim = surface-dimLightHighContrast,
    surface-bright = surface-brightLightHighContrast,
    surface-container-lowest = surface-container-lowestLightHighContrast,
    surface-container-low = surface-container-lowLightHighContrast,
    surface-container = surface-containerLightHighContrast,
    surface-container-high = surface-container-highLightHighContrast,
    surface-container-highest = surface-container-highestLightHighContrast,
)

private val lightMediumContrastScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    surface-tint = surface-tintLightMediumContrast,
    on-primary = on-primaryLightMediumContrast,
    primary-container = primary-containerLightMediumContrast,
    on-primary-container = on-primary-containerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    on-secondary = on-secondaryLightMediumContrast,
    secondary-container = secondary-containerLightMediumContrast,
    on-secondary-container = on-secondary-containerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    on-tertiary = on-tertiaryLightMediumContrast,
    tertiary-container = tertiary-containerLightMediumContrast,
    on-tertiary-container = on-tertiary-containerLightMediumContrast,
    error = errorLightMediumContrast,
    on-error = on-errorLightMediumContrast,
    error-container = error-containerLightMediumContrast,
    on-error-container = on-error-containerLightMediumContrast,
    background = backgroundLightMediumContrast,
    on-background = on-backgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    on-surface = on-surfaceLightMediumContrast,
    surface-variant = surface-variantLightMediumContrast,
    on-surface-variant = on-surface-variantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outline-variant = outline-variantLightMediumContrast,
    shadow = shadowLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverse-surface = inverse-surfaceLightMediumContrast,
    inverse-on-surface = inverse-on-surfaceLightMediumContrast,
    inverse-primary = inverse-primaryLightMediumContrast,
    primary-fixed = primary-fixedLightMediumContrast,
    on-primary-fixed = on-primary-fixedLightMediumContrast,
    primary-fixed-dim = primary-fixed-dimLightMediumContrast,
    on-primary-fixed-variant = on-primary-fixed-variantLightMediumContrast,
    secondary-fixed = secondary-fixedLightMediumContrast,
    on-secondary-fixed = on-secondary-fixedLightMediumContrast,
    secondary-fixed-dim = secondary-fixed-dimLightMediumContrast,
    on-secondary-fixed-variant = on-secondary-fixed-variantLightMediumContrast,
    tertiary-fixed = tertiary-fixedLightMediumContrast,
    on-tertiary-fixed = on-tertiary-fixedLightMediumContrast,
    tertiary-fixed-dim = tertiary-fixed-dimLightMediumContrast,
    on-tertiary-fixed-variant = on-tertiary-fixed-variantLightMediumContrast,
    surface-dim = surface-dimLightMediumContrast,
    surface-bright = surface-brightLightMediumContrast,
    surface-container-lowest = surface-container-lowestLightMediumContrast,
    surface-container-low = surface-container-lowLightMediumContrast,
    surface-container = surface-containerLightMediumContrast,
    surface-container-high = surface-container-highLightMediumContrast,
    surface-container-highest = surface-container-highestLightMediumContrast,
)

private val darkScheme = darkColorScheme(
    primary = primaryDark,
    surface-tint = surface-tintDark,
    on-primary = on-primaryDark,
    primary-container = primary-containerDark,
    on-primary-container = on-primary-containerDark,
    secondary = secondaryDark,
    on-secondary = on-secondaryDark,
    secondary-container = secondary-containerDark,
    on-secondary-container = on-secondary-containerDark,
    tertiary = tertiaryDark,
    on-tertiary = on-tertiaryDark,
    tertiary-container = tertiary-containerDark,
    on-tertiary-container = on-tertiary-containerDark,
    error = errorDark,
    on-error = on-errorDark,
    error-container = error-containerDark,
    on-error-container = on-error-containerDark,
    background = backgroundDark,
    on-background = on-backgroundDark,
    surface = surfaceDark,
    on-surface = on-surfaceDark,
    surface-variant = surface-variantDark,
    on-surface-variant = on-surface-variantDark,
    outline = outlineDark,
    outline-variant = outline-variantDark,
    shadow = shadowDark,
    scrim = scrimDark,
    inverse-surface = inverse-surfaceDark,
    inverse-on-surface = inverse-on-surfaceDark,
    inverse-primary = inverse-primaryDark,
    primary-fixed = primary-fixedDark,
    on-primary-fixed = on-primary-fixedDark,
    primary-fixed-dim = primary-fixed-dimDark,
    on-primary-fixed-variant = on-primary-fixed-variantDark,
    secondary-fixed = secondary-fixedDark,
    on-secondary-fixed = on-secondary-fixedDark,
    secondary-fixed-dim = secondary-fixed-dimDark,
    on-secondary-fixed-variant = on-secondary-fixed-variantDark,
    tertiary-fixed = tertiary-fixedDark,
    on-tertiary-fixed = on-tertiary-fixedDark,
    tertiary-fixed-dim = tertiary-fixed-dimDark,
    on-tertiary-fixed-variant = on-tertiary-fixed-variantDark,
    surface-dim = surface-dimDark,
    surface-bright = surface-brightDark,
    surface-container-lowest = surface-container-lowestDark,
    surface-container-low = surface-container-lowDark,
    surface-container = surface-containerDark,
    surface-container-high = surface-container-highDark,
    surface-container-highest = surface-container-highestDark,
)

private val darkHighContrastScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    surface-tint = surface-tintDarkHighContrast,
    on-primary = on-primaryDarkHighContrast,
    primary-container = primary-containerDarkHighContrast,
    on-primary-container = on-primary-containerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    on-secondary = on-secondaryDarkHighContrast,
    secondary-container = secondary-containerDarkHighContrast,
    on-secondary-container = on-secondary-containerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    on-tertiary = on-tertiaryDarkHighContrast,
    tertiary-container = tertiary-containerDarkHighContrast,
    on-tertiary-container = on-tertiary-containerDarkHighContrast,
    error = errorDarkHighContrast,
    on-error = on-errorDarkHighContrast,
    error-container = error-containerDarkHighContrast,
    on-error-container = on-error-containerDarkHighContrast,
    background = backgroundDarkHighContrast,
    on-background = on-backgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    on-surface = on-surfaceDarkHighContrast,
    surface-variant = surface-variantDarkHighContrast,
    on-surface-variant = on-surface-variantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outline-variant = outline-variantDarkHighContrast,
    shadow = shadowDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverse-surface = inverse-surfaceDarkHighContrast,
    inverse-on-surface = inverse-on-surfaceDarkHighContrast,
    inverse-primary = inverse-primaryDarkHighContrast,
    primary-fixed = primary-fixedDarkHighContrast,
    on-primary-fixed = on-primary-fixedDarkHighContrast,
    primary-fixed-dim = primary-fixed-dimDarkHighContrast,
    on-primary-fixed-variant = on-primary-fixed-variantDarkHighContrast,
    secondary-fixed = secondary-fixedDarkHighContrast,
    on-secondary-fixed = on-secondary-fixedDarkHighContrast,
    secondary-fixed-dim = secondary-fixed-dimDarkHighContrast,
    on-secondary-fixed-variant = on-secondary-fixed-variantDarkHighContrast,
    tertiary-fixed = tertiary-fixedDarkHighContrast,
    on-tertiary-fixed = on-tertiary-fixedDarkHighContrast,
    tertiary-fixed-dim = tertiary-fixed-dimDarkHighContrast,
    on-tertiary-fixed-variant = on-tertiary-fixed-variantDarkHighContrast,
    surface-dim = surface-dimDarkHighContrast,
    surface-bright = surface-brightDarkHighContrast,
    surface-container-lowest = surface-container-lowestDarkHighContrast,
    surface-container-low = surface-container-lowDarkHighContrast,
    surface-container = surface-containerDarkHighContrast,
    surface-container-high = surface-container-highDarkHighContrast,
    surface-container-highest = surface-container-highestDarkHighContrast,
)

private val darkMediumContrastScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    surface-tint = surface-tintDarkMediumContrast,
    on-primary = on-primaryDarkMediumContrast,
    primary-container = primary-containerDarkMediumContrast,
    on-primary-container = on-primary-containerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    on-secondary = on-secondaryDarkMediumContrast,
    secondary-container = secondary-containerDarkMediumContrast,
    on-secondary-container = on-secondary-containerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    on-tertiary = on-tertiaryDarkMediumContrast,
    tertiary-container = tertiary-containerDarkMediumContrast,
    on-tertiary-container = on-tertiary-containerDarkMediumContrast,
    error = errorDarkMediumContrast,
    on-error = on-errorDarkMediumContrast,
    error-container = error-containerDarkMediumContrast,
    on-error-container = on-error-containerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    on-background = on-backgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    on-surface = on-surfaceDarkMediumContrast,
    surface-variant = surface-variantDarkMediumContrast,
    on-surface-variant = on-surface-variantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outline-variant = outline-variantDarkMediumContrast,
    shadow = shadowDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverse-surface = inverse-surfaceDarkMediumContrast,
    inverse-on-surface = inverse-on-surfaceDarkMediumContrast,
    inverse-primary = inverse-primaryDarkMediumContrast,
    primary-fixed = primary-fixedDarkMediumContrast,
    on-primary-fixed = on-primary-fixedDarkMediumContrast,
    primary-fixed-dim = primary-fixed-dimDarkMediumContrast,
    on-primary-fixed-variant = on-primary-fixed-variantDarkMediumContrast,
    secondary-fixed = secondary-fixedDarkMediumContrast,
    on-secondary-fixed = on-secondary-fixedDarkMediumContrast,
    secondary-fixed-dim = secondary-fixed-dimDarkMediumContrast,
    on-secondary-fixed-variant = on-secondary-fixed-variantDarkMediumContrast,
    tertiary-fixed = tertiary-fixedDarkMediumContrast,
    on-tertiary-fixed = on-tertiary-fixedDarkMediumContrast,
    tertiary-fixed-dim = tertiary-fixed-dimDarkMediumContrast,
    on-tertiary-fixed-variant = on-tertiary-fixed-variantDarkMediumContrast,
    surface-dim = surface-dimDarkMediumContrast,
    surface-bright = surface-brightDarkMediumContrast,
    surface-container-lowest = surface-container-lowestDarkMediumContrast,
    surface-container-low = surface-container-lowDarkMediumContrast,
    surface-container = surface-containerDarkMediumContrast,
    surface-container-high = surface-container-highDarkMediumContrast,
    surface-container-highest = surface-container-highestDarkMediumContrast,
)

@Immutable
data class ColorFamily(
    val color: Color,
    val onColor: Color,
    val colorContainer: Color,
    val onColorContainer: Color
)

val unspecified_scheme = ColorFamily(
    Color.Unspecified, Color.Unspecified, Color.Unspecified, Color.Unspecified
)

@Composable
fun AppTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    dynamicColor: Boolean = true,
    content: @Composable () -> Unit
) {
    val colorScheme = when {
        dynamicColor && Build.VERSION.SDK_INT >= Build.VERSION_CODES.S -> {
            val context = LocalContext.current
            if (darkTheme) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
        }
        darkTheme -> darkScheme
        else -> lightScheme
    }

    MaterialTheme(
        colorScheme = colorScheme,
        typography = AppTypography,
        content = content
    )
}